Fix for NoClassDefFoundError on the final build
Error log:

Caused by: java.lang.NoClassDefFoundError:
scala/actors/threadpool/Arrays
at

sidben.ateliercanvas.handler.ConfigurationHandler.getPaintingsInConfigFolderNotInstalled(ConfigurationHandler.java:205)
~[ConfigurationHandler.class:?]